// Generated by https://quicktype.io

export interface LotaipInterface {
    year:         number;
    month:        number;
    detailLotaip: DetailLotaip[];
}

export interface DetailLotaip {
    idCatalogLotaip: number;
    documentsDetail: DocumentsDetail[];
}

export interface DocumentsDetail {
    title:            string;
    url:              string;
    fileName:         string;
    ext:              string;
    idCatalogLiteral: number;
    idDetailLotaip:   number;
}
